%%
% OENG1116 A2: PART-1 MOCK-UP: Huperplane with dots, which side? 
% Classify points, randomly generated by MATLAB!
% ----------------------------------------------------------------------
% Designed by Prof Pavel M.Trivailo (C) 2021
% ----------------------------------------------------------------------
% RECOMMENDED INSTRUCTIONS: Place coursor in Esitor in the first cell.
% Continuously, at least 3 times, Press: Ctrl+Shift+ENTER 
% (to run script from Editor, not Command Window)
% ----------------------------------------------------------------------
clear; close all; clc;
xmin=-2; xmax=10;
x=[xmin xmax];
aa=-0.5; bb=4; %y=-0.5*x+4;
y=aa*x+bb;

xspan=round(xmax)-round(xmin);
ymid=mean(y); ymin=ymid-xspan/2; ymax=ymid+xspan/2;

points=[0 1; 0 3; 2 2; 4 0; 6 0; 2 4; 4 4; 5 3; 8 1; 8 2];

NN=size(points,1);
for ii=1:NN
   fprintf('== GIVEN POINT #%2i: [%g %g] ========\n',ii,points(ii,:));
end

%-----
fig=figure; hold on;
set(fig,'Position', [970  417  560  420]);
plot(x,y,'k','LineWidth',4); grid on;
axis([xmin-1 xmax+1 ymin-1 ymax+1]); axis square;
xl=xlabel('$x$'); yl=ylabel('$y$'); 
str=sprintf('$y = %g x + %g$',aa,bb);
tit=title(str);
set([xl,yl,tit],'Interpreter','LaTeX');

for ii=1:NN
ll(ii)=line('XData',points(ii,1),'YData',points(ii,2),...
    'LineStyle','none','LineWidth',2,...
    'Marker','o','MarkerSize',22,...
    'MarkerFaceColor','y','MarkerEdgeColor','r');
end
set(gca,'FontSize',16);

%%
a=aa; b=-1; c=bb;
af = @(x,y) a*x+b*y+c;
for ii=1:NN
    xi=points(ii,1); yi=points(ii,2);
    afi=af(xi,yi);
    values(ii)=afi;
    txt(ii)=text('String',sprintf('%g',afi),'Position',[xi,yi],...
        'HorizontalAlignment','center','VerticalAlignment','middle');
end
disp(values)
%%
j=10; % dummy variable to be used for incremental plotting

xMaxRandi=round(xmax)-round(xmin)+1;
yMaxRandi=round(ymax)-round(ymin)+1;
xRandi=randi(xMaxRandi,1,1);
yRandi=randi(yMaxRandi,1,1);
xi=xRandi+round(xmin)-1;
yi=yRandi+round(ymin)-1;
disp(sprintf('== RANDOMLY GENERATED POINT: [%g %g] ========',xi,yi))
NN=NN+1;
ll(NN)=line('XData',xi,'YData',yi,...
    'LineStyle','none','LineWidth',4,...
    'Marker','o','MarkerSize',25,...
    'MarkerFaceColor','y','MarkerEdgeColor','m');
    afi=af(xi,yi);
    values(NN)=afi;
    txt(NN)=text('String',sprintf('%g',afi),'Position',[xi,yi],...
                 'HorizontalAlignment','center','VerticalAlignment','middle',...
                 'FontWeight','bold','Color','r');
    points=[points; xi yi];

for ii=1:NN
    if values(ii)>0,
        set(ll(ii),'MarkerFaceColor',[0 1 0],...
                   'MarkerEdgeColor',[0 0 1])
    end
end
set(ll(NN),'MarkerEdgeColor','k');    

